config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#top"
  resources :creators, only:[:new, :create, :show]

  resources :rooms, onl: [:show, :create] do
    resources :messages, only: [:create]
  end
end

app/models/creator.rb
class Creator < ApplicationRecord
  belongs_to :user
  has_many :rooms
  has_many :messages
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController

  def new
    @creator = Creator.new
  end

  def create
    @creator = Creator.new(creator_params)
    @creator["user_id"] = current_user.id
    if @creator.save
      redirect_to creator_path(@creator.id)
    end
  end

  def show
    @creator = Creator.find(params[:id])
    @rooms = @creator.rooms
    unless current_user.creator
      rooms = current_user.rooms
      #自分が入ってるroomの相手のidを格納する
      @creator_ids = []
      rooms.each do |r|
        @creator_ids << r.creator_id
      end
    else
      rooms = current_user.creator.rooms
      #自分が入ってるroomの相手のidを格納する
      @user_ids = []
      rooms.each do |r|
        @user_ids << r.user_id
      end
    end
  end

  private
  def creator_params
    params.require(:creator).permit(:name)
  end
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/views/creators/new.html.haml
= form_with model: @creator,  local: true do |f|
  = f.text_field :name
  = f.submit "Get started",value: "Get started", class:"creator-new-link__submit"

app/views/creators/show.html.haml
- unless current_user.creator
  - if @creator_ids.include?(@creator.id)
    = link_to "chat", room_path(current_user.rooms.find_by(creator_id: @creator.id))
    
  -else
    = form_for Room.new do |f|
      = f.hidden_field :creator_id, :value => @creator.id
      = f.submit
- else
  